# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gut < Formula
  desc "Gut is an easy to use Git client for the command line."
  homepage "https://gut-cli.dev"
  version "0.3.2"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/julien040/gut/releases/download/0.3.2/gut_Darwin_x86_64.tar.gz"
      sha256 "813d816decd84948dfc490ab11553b8261ec023e5613669e4bfe1e96ff91000d"

      def install
        bin.install "gut"
      end
    end
    on_arm do
      url "https://github.com/julien040/gut/releases/download/0.3.2/gut_Darwin_arm64.tar.gz"
      sha256 "35d6bff5303ca26e7992d1abbf51541394a25efdea2944f6e398451a6a7f0e3a"

      def install
        bin.install "gut"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/julien040/gut/releases/download/0.3.2/gut_Linux_x86_64.tar.gz"
        sha256 "85360bf7835f62b5e8d1091835398ae1656c736521132b3cc2e3d8a8b1eeda05"

        def install
          bin.install "gut"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/julien040/gut/releases/download/0.3.2/gut_Linux_arm64.tar.gz"
        sha256 "46ecc72a11c229aef5ac83ce936b13b63cb0f546da506f2d79532d4234e08d75"

        def install
          bin.install "gut"
        end
      end
    end
  end
end
